### ISSUE TITLE
Update value types?

### ISSUE THREAD

**Issue by roll** [okfn/opentrials-clinicaltrailsgov-data#4]
For now all plain values are strings. For example we can cast `number_of_arms` as integers (like in xml schema).

Is it good enough to have all as string for now?

**Comment by danfowler** [comment]
@roll it is probably good enough for an initial pass, but, yes, I would expect we would want to cast values to the types we expect them to be based on the schema.

**Comment by pwalsh** [comment]
While in a database, I'd expect all values are typed. Even if they are stored as a json string that will be parsed later.

**Comment by roll** [comment]
Integers:

```
number_of_arms
number_of_groups
enrollment_actual
enrollment_anticipated
```
