### ISSUE TITLE
Expand some dict values?

### ISSUE THREAD

**Issue by roll** [okfn/opentrials-clinicaltrailsgov-data#6]
Some values look like:

```
"oversight_info": {"oversight_info": {...}}
```

So here is two times `key`.

Is it good enough?

**Comment by danfowler** [comment]
If this can be fixed in a straightforward way, I would say fix it.

**Comment by pwalsh** [comment]
Agree that if cases like this are common enough, we could do that cleaning before we write to sqlite. If it is just some more random thing, though, we can clean further down the pipeline.
